### ISSUE TITLE
Unable to read collection into Array 

### ISSUE THREAD

**Issue by craftybones** [Empact/roxml#34]
Hello,

I am facing an issue trying to read book from books into an object.

twist@tintin /tmp/go >cat books.rb 

require 'rubygems'
require 'roxml'

class Publisher
  include ROXML
  xml_reader :name
end

class Book
  include ROXML
end

class Library
  include ROXML
  xml_reader :books, :as=>[Book]
end

text="<library><books><book>foo</book><book>bar</book><books/><library/>"
lib = Library.from_xml(text)
puts lib.books.size

twist@tintin /tmp/go >which ruby
/home/twist/.rvm/rubies/ruby-1.8.7-p334/bin/ruby

twist@tintin /tmp/go >ruby books.rb 
1

The expected output should be 2 in this case and not 1.

I am using 1.8.7 and unable to run specs. I looked at the log and found that the tests were only 1.8.7 compatible. Can somebody confirm this issue on 1.8.7?

Please let me know.

Thank you,

crafty

**Comment by lostapathy** [comment]
@craftybones I'm guessing you've long since moved on from this.  It appears this code works with current versions of roxml and ruby.  If you're still having issues let me know, otherwise we will close this out.

**Comment by craftybones** [comment]
Of course. Please go ahead. Sorry for the delay.
