### ISSUE TITLE
Please release new gem version

### ISSUE THREAD

**Issue by lostapathy** [Empact/roxml#61]
@Empact can we cut a new gem version that includes the recent fixes to trunk?  Specifically, the ruby-2.4 compatibility changes would get a lot of warnings out of logs for people.

thanks!

**Comment by Empact** [comment]
On it now 👍

**Comment by Empact** [comment]
https://github.com/Empact/roxml/releases/tag/v4.0.0 🎉

**Comment by lostapathy** [comment]
Awesome, thank you!  It hasn't hit https://rubygems.org/gems/roxml but I assume you're still working on that.

**Comment by Empact** [comment]
@lostapathy should be up now 👍

**Comment by lostapathy** [comment]
yep, thanks again!
