### ISSUE TITLE
Please release a new gem version

### ISSUE THREAD

**Issue by anaprimawaty** [Empact/roxml#64]
Please release a new gem version to accommodate the BigDecimal changes, thanks!

**Comment by ianwremmel** [comment]
Are there any plans to release https://github.com/Empact/roxml/pull/62?

**Comment by mmcnickle-float** [comment]
@Empact would you have a chance to cut a release soon? The deprecation warning is noisy on ruby 2.6.5 and will block adoption on ruby 2.7.0.

**Comment by jacobjlevine** [comment]
@Empact looks like the fix for this issue is already in master (commit 7fceaccb768ccc715aea536f5818d2f5f320c9df) but hasn't been included in a new gem version. Anything we can do to help with that? It would be great for all us who use quickbooks-ruby to be able to use this gem with Ruby 2.7.

**Comment by jacobjlevine** [comment]
@rmacklin thanks for your work on updating this gem last year. Any chance you have some influence here?

**Comment by lostapathy** [comment]
Cutting a gem requires the attention of someone listed as an author over on rubygems - which is separate from github privileges.

To work around this, I've been pointing my Gemfile directly at github at the hash including the fixes I needed.

**Comment by jacobjlevine** [comment]
@lostapathy thanks for the info! Looks like you're an admin for the github repo. Is @Empact the only author on rubygems? And any insights into why it's taken so long to move this forward?

Also, thanks for the suggestion for the Gemfile. For anyone else here because they use quickbooks-ruby, I added `gem 'roxml', github: 'Empact/roxml', ref: '0d6fd8e'` and that seems to have fixed errors with quickbooks-ruby and Ruby 2.7.

**Comment by lostapathy** [comment]
There's 4 authors listed over [on rubygems](https://rubygems.org/gems/roxml) but I think Empact is by far the most recent person to participate here.

**Comment by rmacklin** [comment]
> @rmacklin thanks for your work on updating this gem last year. Any chance you have some influence here?

Unfortunately I can't help either. I've also been using a git ref in my Gemfile to work around the gem not having a new release on rubygems.

**Comment by Empact** [comment]
I can release this today. Does anyone want to step up as a maintainer?

**Comment by rmacklin** [comment]
> I can release this today.

Thank you, that would be great!

> Does anyone want to step up as a maintainer?

I would defer to those who already have push access (e.g. @lostapathy).

Even though I was tagged in this thread, I don't really have experience with this gem. It's only in our application as a transitive dependency, so I've never worked with it directly. I opened #62 to fix the `BigDecimal` deprecations when I was upgrading our application to ruby 2.6 and that small change was the extent of my contributions.

That said, I could help out with cutting and publishing releases.

One thought: asking for a new maintainer might warrant its own dedicated issue which could potentially be linked from the top of the README.

**Comment by Empact** [comment]
Released:
https://rubygems.org/gems/roxml
https://github.com/Empact/roxml/releases/tag/v4.1.0

Let me know if you run into any issues with the release, will be prompt next time.

Thanks all for the help - it takes a village. ;)
